version: '3.8'

services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/venv
    environment:
      - PYTHONUNBUFFERED=1
    command: bash

  test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
      - /app/venv
    environment:
      - PYTHONUNBUFFERED=1

  prod:
    build:
      context: .
      target: prod
    environment:
      - PYTHONUNBUFFERED=1
